# Generated by Django 4.0.3 on 2022-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shine',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='샤인학원학생'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='부모성함'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='부모전화번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='학년'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='학교이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='생년월일'),
        ),
    ]
