# Generated by Django 4.0.3 on 2022-03-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='servicePolicy',
        ),
        migrations.AlterField(
            model_name='user',
            name='personalPolicy',
            field=models.BooleanField(default=False, verbose_name='개인정보호정책/이용약관'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='생년월일'),
        ),
    ]
