# Generated by Django 4.0.3 on 2022-03-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_servicepolicy_alter_user_personalpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_black',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='블랙'),
        ),
    ]
