# Generated by Django 4.0.3 on 2022-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_user_image_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deviceId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='디바이스아이디'),
        ),
    ]
