# Generated by Django 4.0.3 on 2022-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrauthcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='qrauthcode'),
        ),
        migrations.AddField(
            model_name='user',
            name='qrtime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='qrtime'),
        ),
    ]
