# Generated by Django 4.0.3 on 2022-04-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_qrauthcode_user_qrtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_shine',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남', '남'), ('여', '여')], max_length=50, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('관리자', '관리자'), ('일반', '일반'), ('학생', '학생')], max_length=50, null=True, verbose_name='회원타입'),
        ),
    ]
