# Generated by Django 4.0.3 on 2022-04-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alrams', '0001_initial'),
        ('users', '0011_remove_user_is_shine_remove_user_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alrams',
            field=models.ManyToManyField(blank=True, null=True, related_name='알림', to='alrams.alram'),
        ),
    ]
