# Generated by Django 4.0.3 on 2022-04-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_alrams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alrams',
        ),
    ]
