# Generated by Django 4.0.3 on 2022-03-23 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '열람실명',
                'verbose_name_plural': '열람실 모음',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '좌석타입',
                'verbose_name_plural': '좌석타입 모음',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='좌석이름')),
                ('lightId', models.CharField(max_length=50, null=True, verbose_name='조명 id')),
                ('is_light_on', models.BooleanField(default=False, max_length=50, verbose_name='조명 상태')),
                ('is_seat_full', models.BooleanField(default=False, max_length=50, verbose_name='좌석 상태')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='회원', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.roomtype', verbose_name='열람실')),
                ('seat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.seattype', verbose_name='좌석타입')),
            ],
            options={
                'verbose_name': '좌석',
                'verbose_name_plural': '좌석 모음',
            },
        ),
    ]
