# Generated by Django 4.0.3 on 2022-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_clean',
            field=models.BooleanField(default=False, max_length=50, verbose_name='짐상태'),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_reservation',
            field=models.BooleanField(default=False, max_length=50, verbose_name='예약'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_title',
            field=models.CharField(max_length=50, null=True, verbose_name='좌석타이틀'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='좌석번호'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S')], max_length=50, null=True, verbose_name='좌석타입'),
        ),
    ]
