# Generated by Django 4.0.3 on 2022-04-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seat_is_clean_seat_is_reservation_seat_seat_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='room_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='열람실'),
        ),
    ]
