# Generated by Django 4.0.3 on 2022-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0004_seat_end_date_alter_seat_lightid_alter_seat_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='is_clean',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True, verbose_name='짐상태'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_light_on',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True, verbose_name='조명 상태'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_reservation',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True, verbose_name='예약'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_seat_full',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True, verbose_name='좌석 상태'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='lightId',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='조명 id'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='좌석타이틀'),
        ),
    ]
