# Generated by Django 4.0.3 on 2022-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0006_alter_seat_seat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='lightId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='조명 id'),
        ),
    ]
