# Generated by Django 4.0.4 on 2022-04-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seats', '0007_alter_seat_lightid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.DeleteModel(
            name='SeatType',
        ),
        migrations.AddField(
            model_name='seat',
            name='room_cate',
            field=models.CharField(choices=[('남', '남'), ('여', '여'), ('공용', '공용')], default='공용', max_length=50, null=True, verbose_name='열람실'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='owner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='회원', to=settings.AUTH_USER_MODEL),
        ),
    ]
