# Generated by Django 4.0.3 on 2022-04-10 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seatName', models.CharField(max_length=50, null=True, verbose_name='좌석번호')),
                ('check_type', models.CharField(choices=[('입실', '입실'), ('퇴실', '퇴실')], max_length=50, null=True, verbose_name='입실타입')),
                ('seatUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='입실회원')),
            ],
            options={
                'verbose_name': '입실기록',
                'verbose_name_plural': '입실기록 모음',
            },
        ),
    ]
