# Generated by Django 4.0.3 on 2022-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertifies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertifie',
            name='limitTime',
            field=models.DateTimeField(null=True, verbose_name='제한시간'),
        ),
    ]
