# Generated by Django 4.0.3 on 2022-04-10 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(null=True, verbose_name='내용')),
                ('complaintype', models.CharField(choices=[('요청', '요청'), ('답변', '답변')], max_length=50, null=True, verbose_name='요청타입')),
            ],
            options={
                'verbose_name': '회원타입',
                'verbose_name_plural': '회원타입 모음',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('content', models.ManyToManyField(null=True, to='complaints.complainttype', verbose_name='요청사항')),
            ],
            options={
                'verbose_name': '컴플레인',
                'verbose_name_plural': '컴플레인 모음',
            },
        ),
    ]
