# Generated by Django 4.0.3 on 2022-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='answer',
            field=models.TextField(null=True, verbose_name='답변'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaintype',
            field=models.CharField(choices=[('요청', '요청'), ('답변', '답변')], max_length=50, null=True, verbose_name='요청타입'),
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='content',
        ),
        migrations.AddField(
            model_name='complaint',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.DeleteModel(
            name='ComplaintType',
        ),
    ]
