# Generated by Django 4.0.3 on 2022-04-06 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seats', '0004_seat_end_date_alter_seat_lightid_alter_seat_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='구매자이름')),
                ('buyer_tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='구매자전화번호')),
                ('howmanyDate', models.PositiveIntegerField(blank=True, null=True, verbose_name='주문일수')),
                ('merchant_uid', models.CharField(blank=True, help_text='수기 입력은 빈칸', max_length=100, null=True, verbose_name='구매번호')),
                ('imp_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='아임포트구매번호')),
                ('paid_at', models.PositiveIntegerField(blank=True, null=True, verbose_name='승인일시')),
                ('pg_provider', models.CharField(blank=True, choices=[('kakaopay', '카카오페이'), ('html5_inicis', '이니시스')], max_length=100, null=True, verbose_name='PG사')),
                ('pg_tid', models.CharField(blank=True, max_length=100, null=True, verbose_name='PG승인일시')),
                ('receipt_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='영수증')),
                ('status', models.CharField(blank=True, choices=[('paid', '승인'), ('ready', '준비'), ('accountready', '계좌이체준비'), ('failed', '실패'), ('cancelled', '취소')], default='ready', max_length=100, null=True, verbose_name='결재상태')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='총결재금액')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderseat', to='seats.seat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 모음',
                'ordering': ['-created'],
            },
        ),
    ]
