# Generated by Django 4.0.3 on 2022-04-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True, verbose_name='타이틀')),
                ('subTitle', models.TextField(null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 모음',
                'ordering': ['-created'],
            },
        ),
    ]
