# Generated by Django 4.0.3 on 2022-04-09 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alram',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='유져', to=settings.AUTH_USER_MODEL),
        ),
    ]
